"""Initial migration of Course Rating Model.

Revision ID: 0b15b5bb9402
Revises: 31d1e3c8db1e
Create Date: 2026-10-10 10:50:37.692582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b15b5bb9402'
down_revision = '31d1e3c8db1e'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('Course_Rating',
    sa.Column('course_rating_id', sa.Integer(), nullable=False),
    sa.Column('tee_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hole_count', sa.Integer(), server_default='18', nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', name='course_rating_gender'), server_default='M', nullable=False),
    sa.Column('start_hole', sa.Integer(), server_default='1', nullable=False),
    sa.Column('course_rating', sa.FLOAT(), nullable=False),
    sa.Column('slope', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('bogey_rating', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tee_id'], ['Tee.tee_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_rating_id'),
    sa.CheckConstraint('start_hole >= 1 AND start_hole <= 18', name=op.f('check_course_rating_start_hole')),
    sa.CheckConstraint('slope >= 55 AND slope <= 155', name=op.f('check_course_rating_slope')),
    sa.CheckConstraint('par >= 27 AND par <= 80', name=op.f('check_course_rating_par')),
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('Course_Rating')
  # ### end Alembic commands ###
