"""Initial migration of Tee Model.

Revision ID: 31d1e3c8db1e
Revises: c40e3bd9d7b0
Create Date: 2026-10-10 10:30:15.650063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d1e3c8db1e'
down_revision = 'c40e3bd9d7b0'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('Tee',
    sa.Column('tee_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('stack_tee_id', sa.String(length=25), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('yards', sa.Integer(), server_default='7200', nullable=False),
    sa.Column('meters', sa.Integer(), server_default='6600', nullable=False),
    sa.Column('hole_count', sa.Integer(), server_default='18', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tee_id'),
    sa.UniqueConstraint('stack_tee_id'),
    sa.CheckConstraint('yards > 0', name=op.f('check_tee_yards')),
    sa.CheckConstraint('meters > 0', name=op.f('check_tee_meters')),
    sa.CheckConstraint('hole_count >= 1 AND hole_count <= 18', name=op.f('check_tee_hole_count'))
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('Tee')
  # ### end Alembic commands ###
