"""Initial migration of equipment specs model

Revision ID: 3d2ad1c26047
Revises: 23b1f9915e84
Create Date: 2026-02-22 15:06:25.993755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d2ad1c26047'
down_revision = '23b1f9915e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Equipment_Spec',
    sa.Column('equipment_spec_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('loft', sa.FLOAT(), nullable=True),
    sa.Column('lie', sa.FLOAT(), nullable=True),
    sa.Column('club_length', sa.FLOAT(), nullable=True),
    sa.Column('wieght', sa.FLOAT(), nullable=True),
    sa.Column('club_head', sa.String(length=50), nullable=True),
    sa.Column('head_weight', sa.FLOAT(), nullable=True),
    sa.Column('club_offset', sa.FLOAT(), nullable=True),
    sa.Column('bounce', sa.FLOAT(), nullable=True),
    sa.Column('swing_weight', sa.String(length=2), nullable=True),
    sa.Column('shaft', sa.String(length=50), nullable=True),
    sa.Column('shaft_flex', sa.String(length=5), nullable=True),
    sa.Column('shaft_weight', sa.FLOAT(), nullable=True),
    sa.Column('grip', sa.String(length=50), nullable=True),
    sa.Column('grip_core_dia', sa.FLOAT(), nullable=True),
    sa.Column('grip_weight', sa.FLOAT(), nullable=True),
    sa.Column('grip_size', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['Equipment.equipment_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipment_spec_id'),
    sa.UniqueConstraint('equipment_spec_id')
    )

def downgrade():
    op.drop_table('Equipment_Spec')
