"""Initial Migration of the facility model

Revision ID: 738fd119aceb
Revises: 
Create Date: 2025-10-26 17:26:42.454127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738fd119aceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Facility',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('handle', sa.String(length=25), nullable=False),
    sa.Column('classification', sa.Enum('D', 'P', 'R', 'M', 'S', 'O', name='facility_classification'), server_default='O', nullable=False),
    sa.Column('hole_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('established', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('geo_lat', sa.FLOAT(), nullable=True),
    sa.Column('geo_lon', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()),
    sa.PrimaryKeyConstraint('facility_id'),
    sa.UniqueConstraint('facility_id'),
    sa.UniqueConstraint('handle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Facility')
    # ### end Alembic commands ###
