"""Initial migration of handicap history model.

Revision ID: 9e5ca252a55a
Revises: 048f06b86d4d
Create Date: 2026-03-14 05:32:09.799570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e5ca252a55a'
down_revision = '048f06b86d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Handicap_History',
        sa.Column('handicap_history_id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column('ghin_number', sa.String(length=10), nullable=False),
        sa.Column('rev_date', db.Date()),
        sa.Column('assoc', sa.String(length=25), nullable=True),
        sa.Column('club', sa.String(length=50), nullable=True),
        sa.Column('hard_soft_cap', sa.String(length=3), server_default='N', nullable=False),
        sa.Column('hard_cap', sa.String(length=3), server_default='N', nullable=False),
        sa.Column('soft_cap', sa.String(length=3), server_default='N', nullable=False),
        sa.Column('hi_displsy', sa.String(length=5), nullable=True),
        sa.Column('hi_value', sa.Float, nullable=True),
        sa.Column('low_hi_displsy', sa.String(length=5), nullable=True),
        sa.Column('low_hi_value', sa.Float, nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['ghin_number'], ['Person.ghin_number'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['person_id'], ['Person.person_id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('handicap_history_id'),
        sa.UniqueConstraint('handicap_history_id'),
    )


def downgrade():
    op.drop_table('Handicap_History')
