"""Initial Migration of the hole_geo model

Revision ID: b316e18c2b6c
Revises: eb48c1e93cbf
Create Date: 2025-10-28 05:25:23.080230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b316e18c2b6c'
down_revision = 'eb48c1e93cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hole_Geo',
    sa.Column('hole_geo_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=25), nullable=False),
    sa.Column('tee_lat', sa.FLOAT(), nullable=True),
    sa.Column('tee_lon', sa.FLOAT(), nullable=True),
    sa.Column('dl_lat', sa.FLOAT(), nullable=True),
    sa.Column('dl_lon', sa.FLOAT(), nullable=True),
    sa.Column('dl2_lat', sa.FLOAT(), nullable=True),
    sa.Column('dl2_lon', sa.FLOAT(), nullable=True),
    sa.Column('green_center_lat', sa.FLOAT(), nullable=True),
    sa.Column('green_center_lon', sa.FLOAT(), nullable=True),
    sa.Column('green_front_lat', sa.FLOAT(), nullable=True),
    sa.Column('green_front_lon', sa.FLOAT(), nullable=True),
    sa.Column('green_back_lat', sa.FLOAT(), nullable=True),
    sa.Column('green_back_lon', sa.FLOAT(), nullable=True),
    sa.Column('zoom', sa.Integer(), nullable=True),
    sa.Column('rotation', sa.FLOAT(), nullable=True),
    sa.Column('green_depth', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handle'], ['Course.handle'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hole_geo_id'),
    sa.UniqueConstraint('hole_geo_id'),
    sa.CheckConstraint('number >= 1 AND number<= 18', name=op.f('check_hole_geo_number')),
    sa.CheckConstraint('tee_lat > -90 AND tee_lat < 90', name=op.f('check_hole_geo_tee_lat')),
    sa.CheckConstraint('tee_lon > -180 AND tee_lon < 180', name=op.f('check_hole_geo_tee_lon')),
    sa.CheckConstraint('dl_lat > -90 AND dl_lat < 90', name=op.f('check_hole_geo_dl_lat')),
    sa.CheckConstraint('dl_lon > -180 AND dl_lon < 180', name=op.f('check_hole_geo_dl_lon')),
    sa.CheckConstraint('dl2_lat > -90 AND dl2_lat < 90', name=op.f('check_hole_geo_dl2_lat')),
    sa.CheckConstraint('dl2_lon > -180 AND dl2_lon < 180', name=op.f('check_hole_geo_dl2_lon')),
    sa.CheckConstraint('green_center_lat > -90 AND green_center_lat < 90', name=op.f('check_hole_geo_green_center_lat')),
    sa.CheckConstraint('green_center_lon > -180 AND green_center_lon < 180', name=op.f('check_hole_geo_green_center_lon')),
    sa.CheckConstraint('green_front_lat > -90 AND green_front_lat < 90', name=op.f('check_hole_geo_green_front_lat')),
    sa.CheckConstraint('green_front_lon > -180 AND green_front_lon < 180', name=op.f('check_hole_geo_green_front_lon')),
    sa.CheckConstraint('green_back_lat > -90 AND green_back_lat < 90', name=op.f('check_hole_geo_green_back_lat')),
    sa.CheckConstraint('green_back_lon > -180 AND green_back_lon < 180', name=op.f('check_hole_geo_green_back_lon')),
    sa.CheckConstraint('zoom >=1 AND zoom <= 20', name=op.f('check_hole_geo_zoom')),
    sa.CheckConstraint('rotation >= 0 AND rotation < 360', name=op.f('check_hole_geo_rotation'))
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table('Hole_Geo')
    # ### end Alembic commands ###
