"""Initial migration of Facility Season Model.

Revision ID: c40e3bd9d7b0
Revises: f38366ce12dc
Create Date: 2026-10-10 10:26:26.317256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40e3bd9d7b0'
down_revision = 'f38366ce12dc'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('Facility_Season',
    sa.Column('facility_season_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('year_round', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['Facility.facility_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('facility_season_id'),
    sa.UniqueConstraint('facility_id'),
    sa.UniqueConstraint('facility_season_id')
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('Facility_Season')
  # ### end Alembic commands ###
