"""Initial migration of Facility Model.

Revision ID: ca57bb199bbc
Revises: 
Create Date: 2026-10-10 10:04:11.542986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca57bb199bbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('Facility',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('stack_facility_id', sa.String(length=25), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.Enum('D', 'P', 'R', 'M', 'S', 'O', name='facility_classification'), server_default='O', nullable=False),
    sa.Column('established', sa.Integer(), nullable=True),
    sa.Column('handle', sa.String(length=25), nullable=False),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('geo_lat', sa.FLOAT(), nullable=True),
    sa.Column('geo_lon', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('facility_id'),
    sa.UniqueConstraint('facility_id'),
    sa.UniqueConstraint('handle'),
    sa.UniqueConstraint('stack_facility_id'),
    sa.CheckConstraint('established > 1400', name=op.f('check_facility_established')),
    sa.CheckConstraint('geo_lat > -90 AND geo_lat < 90', name=op.f('check_facility_geo_lat')),
    sa.CheckConstraint('geo_lon > -180 AND geo_lon < 180', name=op.f('check_facility_geo_lon')),
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('Facility')
  # ### end Alembic commands ###
