"""Initial migration of person model.

Revision ID: e10b3932e9d5
Revises: 35de02397413
Create Date: 2026-01-31 15:29:39.598845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e10b3932e9d5'
down_revision = '35de02397413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Person',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('nation', sa.String(length=5), nullable=True),
    sa.Column('home_facility', sa.Integer(), nullable=False),
    sa.Column('player_type', sa.Enum('A', 'P', 'T', 'C', 'J', name='person_player_type'), server_default='A', nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'O', 'P', name='person_gender'), server_default='P', nullable=False),
    sa.Column('handedness', sa.Enum('L', 'R', name='person_handedness'), server_default='R', nullable=False),
    sa.Column('units_distance', sa.Enum('Y', 'M', name='person_units_distance'), server_default='Y', nullable=False),
    sa.Column('units_speed', sa.Enum('MPH', 'KPH', 'MPS', name='person_units_speed'), server_default='MPH', nullable=False),
    sa.Column('units_temp', sa.Enum('F', 'C', name='person_units_temp'), server_default='F', nullable=False),
    sa.Column('units_weight', sa.Enum('LB', 'KG', 'ST', name='person_units_weight'), server_default='LB', nullable=False),
    sa.Column('units_alt', sa.Enum('FT', 'M', name='person_units_alt'), server_default='FT', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_facility'], ['Facility.facility_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('person_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Person')


    # ### end Alembic commands ###
