"""Initial migration of Hole Model.

Revision ID: ef934b0d0e43
Revises: 0b15b5bb9402
Create Date: 2026-10-10 10:57:35.529414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef934b0d0e43'
down_revision = '0b15b5bb9402'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('hole',
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('tee_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', name='hole_gender'), server_default='M', nullable=False),
    sa.Column('yards', sa.Integer(), server_default='400', nullable=False),
    sa.Column('meters', sa.Integer(), server_default='367', nullable=False),
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('si', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tee_id'], ['Tee.tee_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hole_id'),
    sa.CheckConstraint('number >= 1 AND number <= 18', name=op.f('check_hole_number')),
    sa.CheckConstraint('yards > 0 AND yards <= 999', name=op.f('check_hole_yards')),
    sa.CheckConstraint('meters > 0 AND meters <= 999', name=op.f('check_hole_meters')),
    sa.CheckConstraint('par >= 3 AND par <= 6', name=op.f('check_hole_par')),
    sa.CheckConstraint('si >= 1 AND si <= 18', name=op.f('check_hole_si')),
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('hole')
  # ### end Alembic commands ###
