"""Initial migration of Course  Model.

Revision ID: f38366ce12dc
Revises: ca57bb199bbc
Create Date: 2026-10-10 10:17:33.933831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38366ce12dc'
down_revision = 'ca57bb199bbc'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('Course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('stack_course_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('hole_count', sa.Integer(), server_default='18', nullable=False),
    sa.Column('established', sa.Integer(), nullable=True),
    sa.Column('architect', sa.String(length=100), nullable=True),
    sa.Column('handle', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['Facility.facility_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_id'),
    sa.UniqueConstraint('handle'),
    sa.UniqueConstraint('stack_course_id'),
    sa.CheckConstraint('hole_count >= 1 AND hole_count <= 18', name=op.f('check_course_hole_count')),
    sa.CheckConstraint('established > 1400', name=op.f('check_course_established'))
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('Course')
  # ### end Alembic commands ###
