const CountryList = [
  {country: "Afghanistan", map: "AF", code: "AFG"}, 
  {country: "Albania", map: "AL", code: "ALB"},
  {country: "Algeria", map: "DZ", code: "DZA"},
  {country: "American Samoa", map: "AS", code: "ASM"},
  {country: "Andorra", map: "AD", code: "AND"},
  {country: "Angola", map: "AO", code: "AGO"},
  {country: "Anguilla", map: "AI", code: "AIA"},
  {country: "Antarctica", map: "AQ", code: "ATA"},
  {country: "Antigua and Barbuda", map: "AG", code: "ATG"},
  {country: "Argentina", map: "AR", code: "ARG"},
  {country: "Armenia", map: "AM", code: "ARM"},
  {country: "Aruba", map: "AW", code: "ABW"},
  {country: "Australia", map: "AU", code: "AUS"},
  {country: "Austria", map: "AT", code: "AUT"},
  {country: "Azerbaijan", map: "AZ", code: "AZE"},
  {country: "Bahamas", map: "BS", code: "BHS"},
  {country: "Bahrain", map: "BH", code: "BHR"},
  {country: "Bangladesh", map: "BD", code: "BGD"},
  {country: "Barbados", map: "BB", code: "BRB"},
  {country: "Belarus", map: "BY", code: "BLR"},
  {country: "Belgium", map: "BE", code: "BEL"},
  {country: "Belize", map: "BZ", code: "BLZ"},
  {country: "Benin", map: "BJ", code: "BEN"},
  {country: "Bermuda", map: "BM", code: "BMU"},
  {country: "Bhutan", map: "BT", code: "BTN"},
  {country: "Bolivia", map: "BO", code: "BOL"},
  {country: "Caribbean Netherlands", map: "BQ", code: "BES"},
  {country: "Bosnia and Herzegovina", map: "BA", code: "BIH"},
  {country: "Botswana", map: "BW", code: "BWA"},
  {country: "Bouvet Island", map: "BV", code: "BVT"},
  {country: "Brazil", map: "BR", code: "BRA"},
  {country: "British Indian Ocean Territory", map: "IO", code: "IOT"},
  {country: "Brunei Darussalam", map: "BN", code: "BRN"},
  {country: "Bulgaria", map: "BG", code: "BGR"},
  {country: "Burkina Faso", map: "BF", code: "BFA"},
  {country: "Burundi", map: "BI", code: "BDI"},
  {country: "Cabo Verde", map: "CV", code: "CPV"},
  {country: "Cambodia", map: "KH", code: "KHM"},
  {country: "Cameroon", map: "CM", code: "CMR"},
  {country: "Canada", map: "CA", code: "CAN"},
  {country: "Cayman Islands", map: "KY", code: "CYM"},
  {country: "Central African Republic (", map: "CF", code: "CAF"},
  {country: "Chad", map: "TD", code: "TCD"},
  {country: "Chile", map: "CL", code: "CHL"},
  {country: "China", map: "CN", code: "CHN"},
  {country: "Christmas Island", map: "CX", code: "CXR"},
  {country: "Cocos Islands", map: "CC", code: "CCK"},
  {country: "Colombia", map: "CO", code: "COL"},
  {country: "Comoros", map: "KM", code: "COM"},
  {country: "D.R. of the Congo", map: "CD", code: "COD"},
  {country: "Congo", map: "CG", code: "COG"},
  {country: "Cook Islands", map: "CK", code: "COK"},
  {country: "Costa Rica", map: "CR", code: "CRI"},
  {country: "Croatia", map: "HR", code: "HRV"},
  {country: "Cuba", map: "CU", code: "CUB"},
  {country: "Curaçao", map: "CW", code: "CUW"},
  {country: "Cyprus", map: "CY", code: "CYP"},
  {country: "Czechia", map: "CZ", code: "CZE"},
  {country: "Côte dIvoire", map: "CI", code: "CIV"},
  {country: "Denmark", map: "DK", code: "DNK"},
  {country: "Djibouti", map: "DJ", code: "DJI"},
  {country: "Dominica", map: "DM", code: "DMA"},
  {country: "Dominican Republic", map: "DO", code: "DOM"},
  {country: "Ecuador", map: "EC", code: "ECU"},
  {country: "Egypt", map: "EG", code: "EGY"},
  {country: "El Salvador", map: "SV", code: "SLV"},
  {country: "Equatorial Guinea", map: "GQ", code: "GNQ"},
  {country: "Eritrea", map: "ER", code: "ERI"},
  {country: "Estonia", map: "EE", code: "EST"},
  {country: "Eswatini", map: "SZ", code: "SWZ"},
  {country: "Ethiopia", map: "ET", code: "ETH"},
  {country: "Falkland Islands", map: "FK", code: "FLK"},
  {country: "Faroe Islands", map: "FO", code: "FRO"},
  {country: "Fiji", map: "FJ", code: "FJI"},
  {country: "Finland", map: "FI", code: "FIN"},
  {country: "France", map: "FR", code: "FRA"},
  {country: "French Guiana", map: "GF", code: "GUF"},
  {country: "French Polynesia", map: "PF", code: "PYF"},
  {country: "French Southern Territories", map: "TF", code: "ATF"},
  {country: "Gabon", map: "GA", code: "GAB"},
  {country: "Gambia", map: "GM", code: "GMB"},
  {country: "Georgia", map: "GE", code: "GEO"},
  {country: "Germany", map: "DE", code: "DEU"},
  {country: "Ghana", map: "GH", code: "GHA"},
  {country: "Gibraltar", map: "GI", code: "GIB"},
  {country: "Greece", map: "GR", code: "GRC"},
  {country: "Greenland", map: "GL", code: "GRL"},
  {country: "Grenada", map: "GD", code: "GRD"},
  {country: "Guadeloupe", map: "GP", code: "GLP"},
  {country: "Guam", map: "GU", code: "GUM"},
  {country: "Guatemala", map: "GT", code: "GTM"},
  {country: "Guernsey", map: "GG", code: "GGY"},
  {country: "Guinea", map: "GN", code: "GIN"},
  {country: "Guinea-Bissau", map: "GW", code: "GNB"},
  {country: "Guyana", map: "GY", code: "GUY"},
  {country: "Haiti", map: "HT", code: "HTI"},
  {country: "Heard Island and McDonald Islands", map: "HM", code: "HMD"},
  {country: "Holy See", map: "VA", code: "VAT"},
  {country: "Honduras", map: "HN", code: "HND"},
  {country: "Hong Kong", map: "HK", code: "HKG"},
  {country: "Hungary", map: "HU", code: "HUN"},
  {country: "Iceland", map: "IS", code: "ISL"},
  {country: "India", map: "IN", code: "IND"},
  {country: "Indonesia", map: "ID", code: "IDN"},
  {country: "Iran", map: "IR", code: "IRN"},
  {country: "Iraq", map: "IQ", code: "IRQ"},
  {country: "Ireland", map: "IE", code: "IRL"},
  {country: "Isle of Man", map: "IM", code: "IMN"},
  {country: "Israel", map: "IL", code: "ISR"},
  {country: "Italy", map: "IT", code: "ITA"},
  {country: "Jamaica", map: "JM", code: "JAM"},
  {country: "Japan", map: "JP", code: "JPN"},
  {country: "Jersey", map: "JE", code: "JEY"},
  {country: "Jordan", map: "JO", code: "JOR"},
  {country: "Kazakhstan", map: "KZ", code: "KAZ"},
  {country: "Kenya", map: "KE", code: "KEN"},
  {country: "Kiribati", map: "KI", code: "KIR"},
  {country: "North Korea", map: "KP", code: "PRK"},
  {country: "South Korea", map: "KR", code: "KOR"},
  {country: "Kuwait", map: "KW", code: "KWT"},
  {country: "Kyrgyzstan", map: "KG", code: "KGZ"},
  {country: "Laos", map: "LA", code: "LAO"},
  {country: "Latvia", map: "LV", code: "LVA"},
  {country: "Lebanon", map: "LB", code: "LBN"},
  {country: "Lesotho", map: "LS", code: "LSO"},
  {country: "Liberia", map: "LR", code: "LBR"},
  {country: "Libya", map: "LY", code: "LBY"},
  {country: "Liechtenstein", map: "LI", code: "LIE"},
  {country: "Lithuania", map: "LT", code: "LTU"},
  {country: "Luxembourg", map: "LU", code: "LUX"},
  {country: "Macao", map: "MO", code: "MAC"},
  {country: "Madagascar", map: "MG", code: "MDG"},
  {country: "Malawi", map: "MW", code: "MWI"},
  {country: "Malaysia", map: "MY", code: "MYS"},
  {country: "Maldives", map: "MV", code: "MDV"},
  {country: "Mali", map: "ML", code: "MLI"},
  {country: "Malta", map: "MT", code: "MLT"},
  {country: "Marshall Islands", map: "MH", code: "MHL"},
  {country: "Martinique", map: "MQ", code: "MTQ"},
  {country: "Mauritania", map: "MR", code: "MRT"},
  {country: "Mauritius", map: "MU", code: "MUS"},
  {country: "Mayotte", map: "YT", code: "MYT"},
  {country: "Mexico", map: "MX", code: "MEX"},
  {country: "Micronesia", map: "FM", code: "FSM"},
  {country: "Moldova", map: "MD", code: "MDA"},
  {country: "Monaco", map: "MC", code: "MCO"},
  {country: "Mongolia", map: "MN", code: "MNG"},
  {country: "Montenegro", map: "ME", code: "MNE"},
  {country: "Montserrat", map: "MS", code: "MSR"},
  {country: "Morocco", map: "MA", code: "MAR"},
  {country: "Mozambique", map: "MZ", code: "MOZ"},
  {country: "Myanmar", map: "MM", code: "MMR"},
  {country: "Namibia", map: "NA", code: "NAM"},
  {country: "Nauru", map: "NR", code: "NRU"},
  {country: "Nepal", map: "NP", code: "NPL"},
  {country: "Netherlands", map: "NL", code: "NLD"},
  {country: "New Caledonia", map: "NC", code: "NCL"},
  {country: "New Zealand", map: "NZ", code: "NZL"},
  {country: "Nicaragua", map: "NI", code: "NIC"},
  {country: "Niger", map: "NE", code: "NER"},
  {country: "Nigeria", map: "NG", code: "NGA"},
  {country: "Niue", map: "NU", code: "NIU"},
  {country: "Norfolk Island", map: "NF", code: "NFK"},
  {country: "Northern Mariana Islands", map: "MP", code: "MNP"},
  {country: "Norway", map: "NO", code: "NOR"},
  {country: "Oman", map: "OM", code: "OMN"},
  {country: "Pakistan", map: "PK", code: "PAK"},
  {country: "Palau", map: "PW", code: "PLW"},
  {country: "Palestine", map: "PS", code: "PSE"},
  {country: "Panama", map: "PA", code: "PAN"},
  {country: "Papua New Guinea", map: "PG", code: "PNG"},
  {country: "Paraguay", map: "PY", code: "PRY"},
  {country: "Peru", map: "PE", code: "PER"},
  {country: "Philippines", map: "PH", code: "PHL"},
  {country: "Pitcairn", map: "PN", code: "PCN"},
  {country: "Poland", map: "PL", code: "POL"},
  {country: "Portugal", map: "PT", code: "PRT"},
  {country: "Puerto Rico", map: "PR", code: "PRI"},
  {country: "Qatar", map: "QA", code: "QAT"},
  {country: "North Macedonia", map: "MK", code: "MKD"},
  {country: "Romania", map: "RO", code: "ROU"},
  {country: "Russia", map: "RU", code: "RUS"},
  {country: "Rwanda", map: "RW", code: "RWA"},
  {country: "Réunion", map: "RE", code: "REU"},
  {country: "Saint Barthélemy", map: "BL", code: "BLM"},
  {country: "Saint Helena, Ascension and Tristan da Cunha", map: "SH", code: "SHN"},
  {country: "Saint Kitts and Nevis", map: "KN", code: "KNA"},
  {country: "Saint Lucia", map: "LC", code: "LCA"},
  {country: "French Saint Martin", map: "MF", code: "MAF"},
  {country: "Saint Pierre and Miquelon", map: "PM", code: "SPM"},
  {country: "Saint Vincent and the Grenadines", map: "VC", code: "VCT"},
  {country: "Samoa", map: "WS", code: "WSM"},
  {country: "San Marino", map: "SM", code: "SMR"},
  {country: "Sao Tome and Principe", map: "ST", code: "STP"},
  {country: "Saudi Arabia", map: "SA", code: "SAU"},
  {country: "Senegal", map: "SN", code: "SEN"},
  {country: "Serbia", map: "RS", code: "SRB"},
  {country: "Seychelles", map: "SC", code: "SYC"},
  {country: "Sierra Leone", map: "SL", code: "SLE"},
  {country: "Singapore", map: "SG", code: "SGP"},
  {country: "Dutch Sint Maarten", map: "SX", code: "SXM"},
  {country: "Slovakia", map: "SK", code: "SVK"},
  {country: "Slovenia", map: "SI", code: "SVN"},
  {country: "Solomon Islands", map: "SB", code: "SLB"},
  {country: "Somalia", map: "SO", code: "SOM"},
  {country: "South Africa", map: "ZA", code: "ZAF"},
  {country: "South Georgia and the South Sandwich Islands", map: "GS", code: "SGS"},
  {country: "South Sudan", map: "SS", code: "SSD"},
  {country: "Spain", map: "ES", code: "ESP"},
  {country: "Sri Lanka", map: "LK", code: "LKA"},
  {country: "Sudan", map: "SD", code: "SDN"},
  {country: "Suriname", map: "SR", code: "SUR"},
  {country: "Svalbard and Jan Mayen", map: "SJ", code: "SJM"},
  {country: "Sweden", map: "SE", code: "SWE"},
  {country: "Switzerland", map: "CH", code: "CHE"},
  {country: "Syrian Arab Republic", map: "SY", code: "SYR"},
  {country: "Taiwan", map: "TW", code: "TWN"},
  {country: "Tajikistan", map: "TJ", code: "TJK"},
  {country: "Tanzania", map: "TZ", code: "TZA"},
  {country: "Thailand", map: "TH", code: "THA"},
  {country: "Timor-Leste", map: "TL", code: "TLS"},
  {country: "Togo", map: "TG", code: "TGO"},
  {country: "Tokelau", map: "TK", code: "TKL"},
  {country: "Tonga", map: "TO", code: "TON"},
  {country: "Trinidad and Tobago", map: "TT", code: "TTO"},
  {country: "Tunisia", map: "TN", code: "TUN"},
  {country: "Turkey", map: "TR", code: "TUR"},
  {country: "Turkmenistan", map: "TM", code: "TKM"},
  {country: "Turks and Caicos Islands", map: "TC", code: "TCA"},
  {country: "Tuvalu", map: "TV", code: "TUV"},
  {country: "Uganda", map: "UG", code: "UGA"},
  {country: "Ukraine", map: "UA", code: "UKR"},
  {country: "United Arab Emirates", map: "AE", code: "ARE"},
  {country: "United Kingdom of Great Britain and Northern Ireland", map: "GB", code: "GBR"},
  {country: "United States Minor Outlying Islands", map: "UM", code: "UMI"},
  {country: "United States of America", map: "US", code: "USA"},
  {country: "Uruguay", map: "UY", code: "URY"},
  {country: "Uzbekistan", map: "UZ", code: "UZB"},
  {country: "Vanuatu", map: "VU", code: "VUT"},
  {country: "Venezuela", map: "VE", code: "VEN"},
  {country: "Vietnam", map: "VN", code: "VNM"},
  {country: "British Virgin Islands", map: "VG", code: "VGB"},
  {country: "US Virgin Islands", map: "VI", code: "VIR"},
  {country: "Wallis and Futuna", map: "WF", code: "WLF"},
  {country: "Western Sahara", map: "EH", code: "ESH"},
  {country: "Yemen", map: "YE", code: "YEM"},
  {country: "Zambia", map: "ZM", code: "ZMB"},
  {country: "Zimbabwe", map: "ZW", code: "ZWE"},
  {country: "Åland Islands", map: "AX", code: "ALA"},
  {country: "England", map: "GB-ENG", code: "ENG"},
  {country: "Northern Ireland", map: "GB-NIR", code: "NIR"},
  {country: "Scotland", map: "GB-SCT", code: "SCT"},
  {country: "Wales", map: "GB-WLS", code: "WLS"},
  {country: "United Nations", map: "UN", code: "XXX"},
  {country: "Kosovo", map: "XK", code: "XKR"}
]

export default CountryList