const StateList = [
  {code: 'ak', value: 'Alaska'},
  {code: 'al', value: 'Alabama'},
  {code: 'ar', value: 'Arkansas'},
  {code: 'az', value: 'Arizona'},
  {code: 'ca', value: 'California'},
  {code: 'co', value: 'Colorado'},
  {code: 'ct', value: 'Connecticut'},
  {code: 'de', value: 'Delaware'},
  {code: 'fl', value: 'Florida'},
  {code: 'ga', value: 'Georgia'},
  {code: 'hi', value: 'Hawaii'},
  {code: 'ia', value: 'Iowa'},
  {code: 'id', value: 'Idaho'},
  {code: 'il', value: 'Illinois'},
  {code: 'in', value: 'Indiana'},
  {code: 'ks', value: 'Kansas'},
  {code: 'ky', value: 'Kentucky'},
  {code: 'la', value: 'Louisiana'},
  {code: 'ma', value: 'Massachusetts'},
  {code: 'md', value: 'Maryland'},
  {code: 'me', value: 'Maine'},
  {code: 'mi', value: 'Michigan'},
  {code: 'mn', value: 'Minnesota'},
  {code: 'mo', value: 'Missouri'},
  {code: 'ms', value: 'Mississippi'},
  {code: 'mt', value: 'Montana'},
  {code: 'nc', value: 'North Carolina'},
  {code: 'nd', value: 'North Dakota'},
  {code: 'ne', value: 'Nebraska'},
  {code: 'nh', value: 'New Hampshire'},
  {code: 'nj', value: 'New Jersey'},
  {code: 'nm', value: 'New Mexico'},
  {code: 'nv', value: 'Nevada'},
  {code: 'ny', value: 'New York'},
  {code: 'oh', value: 'Ohio'},
  {code: 'ok', value: 'Oklahoma'},
  {code: 'or', value: 'Oregon'},
  {code: 'pa', value: 'Pennsylvania'},
  {code: 'ri', value: 'Rhode Island'},
  {code: 'sc', value: 'South Carolina'},
  {code: 'sd', value: 'South Dakota'},
  {code: 'tn', value: 'Tennessee'},
  {code: 'tx', value: 'Texas'},
  {code: 'ut', value: 'Utah'},
  {code: 'va', value: 'Virginia'},
  {code: 'vt', value: 'Vermont'},
  {code: 'wa', value: 'Washington'},
  {code: 'wi', value: 'Wisconsin'},
  {code: 'wv', value: 'West Virginia'},
  {code: 'wy', value: 'Wyoming'}
]

export default StateList