const StateList = [
  {code: 'AK', value: 'Alaska'},
  {code: 'AL', value: 'Alabama'},
  {code: 'AR', value: 'Arkansas'},
  {code: 'AZ', value: 'Arizona'},
  {code: 'CA', value: 'California'},
  {code: 'CO', value: 'Colorado'},
  {code: 'CT', value: 'Connecticut'},
  {code: 'DE', value: 'Delaware'},
  {code: 'FL', value: 'Florida'},
  {code: 'GA', value: 'Georgia'},
  {code: 'HI', value: 'Hawaii'},
  {code: 'IA', value: 'Iowa'},
  {code: 'ID', value: 'Idaho'},
  {code: 'IL', value: 'Illinois'},
  {code: 'IN', value: 'Indiana'},
  {code: 'KS', value: 'Kansas'},
  {code: 'KY', value: 'Kentucky'},
  {code: 'LA', value: 'Louisiana'},
  {code: 'MA', value: 'Massachusetts'},
  {code: 'MD', value: 'Maryland'},
  {code: 'ME', value: 'Maine'},
  {code: 'MI', value: 'Michigan'},
  {code: 'MN', value: 'Minnesota'},
  {code: 'MO', value: 'Missouri'},
  {code: 'MS', value: 'Mississippi'},
  {code: 'MT', value: 'Montana'},
  {code: 'NC', value: 'North Carolina'},
  {code: 'ND', value: 'North Dakota'},
  {code: 'NE', value: 'Nebraska'},
  {code: 'NH', value: 'New Hampshire'},
  {code: 'NJ', value: 'New Jersey'},
  {code: 'NM', value: 'New Mexico'},
  {code: 'NV', value: 'Nevada'},
  {code: 'NY', value: 'New York'},
  {code: 'OH', value: 'Ohio'},
  {code: 'OK', value: 'Oklahoma'},
  {code: 'OR', value: 'Oregon'},
  {code: 'PA', value: 'Pennsylvania'},
  {code: 'RI', value: 'Rhode Island'},
  {code: 'SC', value: 'South Carolina'},
  {code: 'SD', value: 'South Dakota'},
  {code: 'TN', value: 'Tennessee'},
  {code: 'TX', value: 'Texas'},
  {code: 'UT', value: 'Utah'},
  {code: 'VA', value: 'Virginia'},
  {code: 'VT', value: 'Vermont'},
  {code: 'WA', value: 'Washington'},
  {code: 'WI', value: 'Wisconsin'},
  {code: 'WV', value: 'West Virginia'},
  {code: 'WY', value: 'Wyoming'}
]

export default StateList