const StateList = [
  {code: 'ak', state: 'Alaska'},
  {code: 'al', state: 'Alabama'},
  {code: 'ar', state: 'Arkansas'},
  {code: 'az', state: 'Arizona'},
  {code: 'ca', state: 'California'},
  {code: 'co', state: 'Colorado'},
  {code: 'ct', state: 'Connecticut'},
  {code: 'de', state: 'Delaware'},
  {code: 'fl', state: 'Florida'},
  {code: 'ga', state: 'Georgia'},
  {code: 'hi', state: 'Hawaii'},
  {code: 'ia', state: 'Iowa'},
  {code: 'id', state: 'Idaho'},
  {code: 'il', state: 'Illinois'},
  {code: 'in', state: 'Indiana'},
  {code: 'ks', state: 'Kansas'},
  {code: 'ky', state: 'Kentucky'},
  {code: 'la', state: 'Louisiana'},
  {code: 'ma', state: 'Massachusetts'},
  {code: 'md', state: 'Maryland'},
  {code: 'me', state: 'Maine'},
  {code: 'mi', state: 'Michigan'},
  {code: 'mn', state: 'Minnesota'},
  {code: 'mo', state: 'Missouri'},
  {code: 'ms', state: 'Mississippi'},
  {code: 'mt', state: 'Montana'},
  {code: 'nc', state: 'North Carolina'},
  {code: 'nd', state: 'North Dakota'},
  {code: 'ne', state: 'Nebraska'},
  {code: 'nh', state: 'New Hampshire'},
  {code: 'nj', state: 'New Jersey'},
  {code: 'nm', state: 'New Mexico'},
  {code: 'nv', state: 'Nevada'},
  {code: 'ny', state: 'New York'},
  {code: 'oh', state: 'Ohio'},
  {code: 'ok', state: 'Oklahoma'},
  {code: 'or', state: 'Oregon'},
  {code: 'pa', state: 'Pennsylvania'},
  {code: 'ri', state: 'Rhode Island'},
  {code: 'sc', state: 'South Carolina'},
  {code: 'sd', state: 'South Dakota'},
  {code: 'tn', state: 'Tennessee'},
  {code: 'tx', state: 'Texas'},
  {code: 'ut', state: 'Utah'},
  {code: 'va', state: 'Virginia'},
  {code: 'vt', state: 'Vermont'},
  {code: 'wa', state: 'Washington'},
  {code: 'wi', state: 'Wisconsin'},
  {code: 'wv', state: 'West Virginia'},
  {code: 'wy', state: 'Wyoming'}
]